### ISSUE TITLE
Values not converting to strings on heroku:set, v1.1.0

### ISSUE THREAD

**Issue by joallard** [laserlemon/figaro#184]
I'm having the same bug as #143.

```
$ figaro heroku:set -p config/variables.yml
/Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/figaro-1.1.0/lib/figaro/cli/heroku_set.rb:7:in `system': no implicit conversion of Fixnum into String (TypeError)
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/figaro-1.1.0/lib/figaro/cli/heroku_set.rb:7:in `run'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/figaro-1.1.0/lib/figaro/cli/task.rb:9:in `run'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/figaro-1.1.0/lib/figaro/cli.rb:38:in `block in <class:CLI>'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jon/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/figaro-1.1.0/bin/figaro:5:in `<top (required)>'
	from /Users/jon/.rbenv/versions/2.1.5/bin/figaro:23:in `load'
	from /Users/jon/.rbenv/versions/2.1.5/bin/figaro:23:in `<main>'
```

**Comment by joallard** [comment]
I just need to point out that this is f—ing annoying, even for the 2 minutes I have to use Figaro. (would be 30 seconds otherwise)

**Comment by albertpak** [comment]
ran into this error last night too, solution in #143 worked

**Comment by joallard** [comment]
Got annoyed by this again, wondering what to do next...

**Comment by albertpak** [comment]
I thought that this was merged in already ( pull request #144 )...but doesnt seem like it

**Comment by joallard** [comment]
Nope. +1

**Comment by laserlemon** [comment]
Are the values in your `application.yml` set as integers or as strings?

**Comment by laserlemon** [comment]
@joallard It's always helpful if you can give me some code to work with: a failing test and/or a proposed solution.

**Comment by joallard** [comment]
Integer or boolean. Here's my code:

```yml
KEY: 1
```

**Comment by laserlemon** [comment]
While I agree that the `heroku:set` command should convert to strings (with warnings) as Figaro does elsewhere, `application.yml` values should also be set to strings. I now have a failing test on this issue but haven't landed on the solution implementation yet.

**Comment by joallard** [comment]
I'd put a `to_s` in there: https://github.com/laserlemon/figaro/blob/master/lib/figaro/cli/heroku_set.rb#L29

**Comment by laserlemon** [comment]
Here's the test I'm adding to `heroku_set_spec.rb`:

```ruby
it "handles non-string values" do
  overwrite_file("config/application.yml", "foo: 4")

  run_simple("figaro heroku:set")

  command = commands.last
  expect(command.name).to eq("heroku")
  expect(command.args).to eq(["config:set", "foo=4"])
end
```

**Comment by fro** [comment]
Same problem here:

    me@host my-project (master) $ figaro heroku:set --remote staging -e staging
    /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/figaro-1.1.1/lib/figaro/cli/heroku_set.rb:7:in `system': no implicit conversion of Fixnum into String (TypeError)
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/figaro-1.1.1/lib/figaro/cli/heroku_set.rb:7:in `run'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/figaro-1.1.1/lib/figaro/cli/task.rb:9:in `run'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/figaro-1.1.1/lib/figaro/cli.rb:38:in `block in <class:CLI>'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/gems/figaro-1.1.1/bin/figaro:5:in `<top (required)>'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/bin/figaro:23:in `load'
    from /Users/me/.rbenv/versions/2.2.0/gemsets/my-project-gems/bin/figaro:23:in `<main>'

    me@host my-project (master) $ bundle | grep figaro
    Using figaro 1.1.1

How did you manage to make this work?

**Comment by libin0120** [comment]
Just check your application.yml file, and for any value showing like numbers, just quote them. For example: 

FACEBOOK_APP_ID: '12345678'
